version: "3.8"

services:
  api-gateway:
    build:
      context: ./
      target: dev
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: npm run start:dev
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
volumes:
  node_modules:


