# Use root/example as user/password credentials for MySQL databases
version: '3.8'

services:

  external-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: humber_bridge
    ports:
      - "33061:3306"
    volumes:
      - ./external-database/data:/var/lib/mysql
      - ./external-database/init:/docker-entrypoint-initdb.d
  
  internal-database:
    image: mysql:5.5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "33062:3306"
    volumes:
      - ./internal-database/data:/var/lib/mysql
      - ./internal-database/init:/docker-entrypoint-initdb.d

  database-ui:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api-gateway:
    build:
      context: ./api-gateway
      target: dev
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: npm run start:dev
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

volumes:
  node_modules:
