# Use root/example as user/password credentials for MySQL databases
version: '3.8'

services:

  external-database:
    image: mysql
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: humber_bridge
    ports:
      - "33061:3306"
    volumes:
      - ./external-database/data:/var/lib/mysql
      - ./external-database/init:/docker-entrypoint-initdb.d
  web-frontend:
    build:
      context: ./web-frontend
    volumes:
    - ./web-frontend:/usr/share/nginx/html
    - ./web-frontend/config:/etc/nginx/conf.d
    ports:
    - "80:80"
  internal-database-test:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=root
      - POSTGRES_DB=humber_bridge
    ports:
      - "33062:5432"

  database-ui:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=external-database

  api-gateway:
    build:
      context: ./api-gateway
      target: dev
    depends_on:
      - internal-database-test
    volumes:
      - ./api-gateway/src:/home/node/app/src
      - ./api-gateway/test:/home/node/app/test
      - ./api-gateway/database:/home/node/app/database
      - node_modules:/home/node/app/node_modules
    command: npm run test:db
    ports:
      - "3030:3000"
      - "9229:9229"
    environment:
      NODE_ENV: development

volumes:
  node_modules:
