# Use root/example as user/password credentials for MySQL databases
version: '3.8'

services:

  external-database:
    image: mysql
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: humber_bridge
    ports:
      - "33061:3306"
    volumes:
      - ./external-database/data:/var/lib/mysql
      - ./external-database/init:/docker-entrypoint-initdb.d
  internal-database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=root
      - POSTGRES_DB=humber_bridge
    ports:
      - "33062:5432"

  database-ui:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=internal-database

  web:
    build:
      context: ./web
      target: dev
    depends_on:
      - internal-database
    init: true
    volumes:
      - ./web:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: npm run start:dev
    ports:
      - "3030:3030"
      - "9229:9229"
    environment:
      NODE_ENV: development

volumes:
  node_modules:
